apiVersion: v1
kind: Service   
metadata:
  name: mv-fe-app-service
  labels:
    app.kubernetes.io/name: mv-fe
    app.kubernetes.io/instance: mv-fe
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    app.kubernetes.io/name: mv-fe
    app.kubernetes.io/instance: mv-fe
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mv-fe-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing # ALB를 공개(internet-facing) 또는 내부(internal)로 설정
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:194722398200:certificate/75bec25f-8f2b-4bee-ab78-a342da07ddc1
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/load-balancer-name: mentoview-ingress-alb
    alb.ingress.kubernetes.io/group.name: mv
    alb.ingress.kubernetes.io/target-type: ip # Pod의 노출된 IP가 Target Group에 매핑
    alb.ingress.kubernetes.io/healthcheck-path: "/" # ALB 타겟 그룹의 헬스 체크 경로
    alb.ingress.kubernetes.io/healthcheck-port: "80"
spec:
  ingressClassName: alb
  rules:
    - host: mentoview.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mv-fe-app-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mv-fe-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mv-fe
      app.kubernetes.io/instance: mv-fe
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mv-fe
        app.kubernetes.io/instance: mv-fe
    spec:
      containers:
      - name: mv-fe-app-container
        image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/mentoview-repo:fe-8ff8bb475f8066568e970fd9c27bf45f59e6c2cc
        ports:
          - protocol: TCP
            containerPort: 80
